name: Pull Latest Submodule Update

on:
  repository_dispatch:
    types: [submodule-updated]

jobs:
  pull_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Clean Git Environment
        run: |
          git config --global --unset core.sparseCheckout || true
          git submodule deinit -f .
          git submodule update --init --recursive

      - name: Update Shared Actions
        run: |
          GIT_TRACE=1 git submodule update --remote --merge --allow-unrelated-histories
          git add .github/actions/shared-actions
          git commit -m "Update to latest shared actions submodule" || echo "No changes to commit"

      - name: Push submodule update
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          git push origin master || echo "No changes to push"
