name: Pull Latest Submodule Update

on:
  repository_dispatch:
    types: [submodule-updated]

jobs:
  update_submodule:
    uses: MarcoMadera/shared-actions/.github/workflows/update-submodule.yml@main
