name: Pull Latest Submodule Update

on:
  repository_dispatch:
    types: [submodule-updated]

jobs:
  pull_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update Shared Actions
        id: update_shared_actions
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          BRANCH_NAME="temp-update-$(date +%Y%m%d%H%M%S)"
          git submodule update --remote
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.BOT_TOKEN }}
          committer: ${{secrets.GIT_USER_NAME}} <${{secrets.GIT_USER_EMAIL}}>
          branch: ${{ env.BRANCH_NAME }}
          title: "Update shared actions submodule"
          commit-message: Update to latest shared actions submodule
          author: ${{secrets.GIT_USER_NAME}} <${{secrets.GIT_USER_EMAIL}}>
          labels: |
            update-modules
          body: "This PR updates the shared actions submodule to the latest commit."
          delete-branch: true
          draft: false
